__author__ = "Femto Trader"
__copyright__ = "Copyright 2015"
__credits__ = [""]
__license__ = "BSD"
__version__ = "0.0.6"
__maintainer__ = "Femto Trader"
__email__ = "femto.trader@gmail.com"
__status__ = "Development"
__url__ = 'https://github.com/ig-python/ig-markets-api-python-library'
