name: trading-ig unit tests

on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
        # python-version: [ "3.10", "3.11", "3.12" ]

    steps:

    - uses: actions/checkout@v6

    - name: Install uv and setup Python
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.11.6"
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --locked --all-extras --dev

    - name: Prettify with black
      uses: psf/black@stable
      with:
        version: "23.3.0"

    - name: Lint with flake8
      run: |
        uv run flake8 trading_ig docs sample tests

    - name: Unit tests with pytest
      run: |
        uv run pytest --ignore=tests/test_integration.py
